### PR TITLE
Chore/if 66 dokerize database setup

### PR DESCRIPTION
**Pull request by LH-Song**
# Description
Setup local PostgreSQL 14 development environment with docker-compose.

# Changes
- Add `docker-compose.yml` with PostgreSQL configuration
- Add `.env.example` for environment variables
- Add `README.md` for setup guide

# Testing Steps
1. `cd .docker/local && cp .env.example .env`
2. `docker-compose up -d`
3. `docker-compose ps` to verify container health

# Checklist
- [x] Environment variables template tested
- [x] Local database starts successfully
- [x] Documentation verified

### CODE REVIEW

**Comment by dex-z** [comment]
Can you provide a bit more context about this Pull request? Supposedly this has been discussed and agreed with Dev team  on how to handle the database setup.

After the PR is approved, when should the PR be merged?

**Comment by LH-Song** [comment]
> Can you provide a bit more context about this Pull request? Supposedly this has been discussed and agreed with Dev team on how to handle the database setup.
> 
> After the PR is approved, when should the PR be merged?

Background and Motivation:
During local development, it’s crucial to have a stable and consistent Postgres database environment. This helps avoid version discrepancies and configuration issues among different team members’ setups. By introducing docker-compose.yml and an .env file, we clearly define local database credentials, database names, and the locations of initialization scripts and configuration files. This ensures that every team member can quickly spin up a uniform database environment locally, reducing time and effort spent dealing with inconsistent setups during testing and development.


**I will reconfirm the above-mentioned details with the development team during our next stand-up meeting. After we have reached a consensus on the approach , I’ll provide you with an update accordingly.**

**Comment by LH-Song** [comment]
> agreed

I’ve spoken with our dev team lead Fan @zhangfanfansz , who confirmed that we will proceed with a Postgres database and tentatively use AWS RDS. He indicated that we can merge this PR into the dev branch whenever we’re ready.

**Review by JuicyASen — DISMISSED** [review]
LGTM

**Review by JuicyASen — DISMISSED** [review]
LGTM

**Review by JuicyASen — APPROVED** [review]
LGTM

**Pull request closed without merging**
